import { db } from "@/db";
import { products } from "@/db/schema";
import { like } from "drizzle-orm";

const FREE_PROJECTS = [
  // 1. SaaS Templates (saas-templates)
  {
    id: "free-shadcn-taxonomy",
    title: "Taxonomy Next.js SaaS Boilerplate - Premium Ready-To-Deploy Template",
    slug: "taxonomy-nextjs-saas-boilerplate",
    shortDescription: "An open-source application built using Next.js 13/14 App Router, Prisma ORM, NextAuth, and Stripe subscriptions.",
    description: "Taxonomy is a complete, production-ready Next.js SaaS template demonstrating standard web application architecture. Features user authentication with NextAuth, database migrations with Prisma, transactional email flows, and a clean Stripe subscription check out flow. Written with state-of-the-art Tailwind CSS UI layouts.",
    category: "saas-templates",
    subcategory: "nextjs-react-boilerplates",
    tags: "nextjs,saas,boilerplate,stripe,prisma",
    thumbnail: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/shadcn-ui/taxonomy/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-vercel-payments",
    title: "Next.js Subscription Payments Boilerplate - Stripe & Supabase SaaS Starter Kit",
    slug: "nextjs-subscription-payments-boilerplate",
    shortDescription: "All-in-one subscription billing starter kit featuring Stripe Checkout, Customer Portal, and Supabase integration.",
    description: "The official Next.js template by Vercel for high-performance subscription billing. Get instant access to integrated Stripe Checkout setups, automated webhook listeners, user profile settings, Stripe Customer Portal redirects, and secure Supabase database bindings.",
    category: "saas-templates",
    subcategory: "nextjs-react-boilerplates",
    tags: "nextjs,stripe,supabase,auth,billing",
    thumbnail: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/vercel/nextjs-subscription-payments/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-fastapi-template",
    title: "FastAPI Production Backend Boilerplate - Advanced High-Performance Python API Framework",
    slug: "fastapi-production-backend-boilerplate",
    shortDescription: "The official full-stack FastAPI starter template with PostgreSQL, SQLModel, React, and Tailwind CSS.",
    description: "An advanced Python backend starter kit powered by FastAPI. Includes pre-configured templates for SQLModel ORM, PostgreSQL, security tokens, automatic user registration, automated OpenAPI docs, and Docker compose files.",
    category: "saas-templates",
    subcategory: "python-backends",
    tags: "fastapi,python,postgresql,docker,api",
    thumbnail: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/tiangolo/full-stack-fastapi-template/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 2. Landing Pages (landing-pages)
  {
    id: "free-precedent",
    title: "Precedent Next.js Marketing Template - High-Converting Waitlist & Launch Page",
    slug: "precedent-nextjs-marketing-template",
    shortDescription: "An opinionated, beautifully designed Next.js launch landing page template optimized for performance.",
    description: "Precedent is a clean product launch landing page built with Next.js App Router, Framer Motion transitions, Lucide React icons, Radix UI primitives, Tailwind CSS styles, and a pre-configured waitlist collection field.",
    category: "landing-pages",
    subcategory: "waitlist-newsletter-pages",
    tags: "nextjs,tailwind,framer-motion,landing",
    thumbnail: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/steven-tey/precedent/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-astrowind",
    title: "AstroWind Premium Landing Page Template - Modern High-Performance Astro Theme",
    slug: "astrowind-premium-landing-page-template",
    shortDescription: "A modern, SEO-friendly landing page template designed with Astro 4.0 and Tailwind CSS.",
    description: "AstroWind is a highly customizable, responsive starter template designed with Astro and Tailwind CSS. Highly optimized for page speed performance, featuring SEO tags setup, blog module, and 100/100 Lighthouse metrics.",
    category: "landing-pages",
    subcategory: "no-code-themes",
    tags: "astro,tailwind,landing,seo,speed",
    thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/onwidget/astrowind/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-tailwind-landing",
    title: "Tailwind Toolbox Marketing Landing Page - Clean Responsive HTML Product Template",
    slug: "tailwind-toolbox-marketing-landing-page",
    shortDescription: "A clean, modern, and highly responsive Tailwind CSS landing page template for product marketing.",
    description: "A responsive HTML landing page template built with Tailwind CSS. Ideal for launching software tools, mobile apps, or digital scripts, containing a feature grid, pricing cards, FAQ accordion, and call-to-action blocks.",
    category: "landing-pages",
    subcategory: "saas-pricing-checkout",
    tags: "tailwind,html,landing,responsive,css",
    thumbnail: "https://images.unsplash.com/photo-1542744094-3a31f08e78ec?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/tailwindtoolbox/Landing-Page/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 3. Scripts & Automations (scripts)
  {
    id: "free-crawlee",
    title: "Crawlee Node.js Resilient Web Scraper & Crawler - Puppeteer, Playwright & Cheerio Automation",
    slug: "crawlee-nodejs-resilient-web-scraper",
    shortDescription: "A web scraping and browser automation library for Node.js to crawl links and extract structured data.",
    description: "Crawlee helps you build resilient web scrapers that bypass anti-scraping blocks automatically. Handles proxy rotation, request queues, request retries, automated link discovery, and structured data storage (JSON/CSV) effortlessly.",
    category: "scripts",
    subcategory: "web-scrapers-crawlers",
    tags: "scraping,crawler,puppeteer,playwright,nodejs",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc51?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/apify/crawlee/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-chrome-boilerplate",
    title: "Chrome Extension React Manifest V3 Boilerplate - Webpack & hot reloading starter",
    slug: "chrome-extension-react-mv3-boilerplate",
    shortDescription: "A premium Manifest V3 extension developer boilerplate with React, Webpack, and hot reloading.",
    description: "Build browser extensions instantly. This starter kit complies with Chrome Manifest V3 regulations and is pre-configured with React, TypeScript, Webpack compilation pipelines, background script setups, and extension popup windows.",
    category: "scripts",
    subcategory: "browser-extensions",
    tags: "chrome,extension,manifest-v3,react,webpack",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/lxieyang/chrome-extension-boilerplate-react/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-docker-compose",
    title: "Docker Awesome Compose Boilerplates - One-Click Production Environment Configurations",
    slug: "docker-awesome-compose-boilerplates",
    shortDescription: "A collection of production-ready Docker Compose environment scripts for PostgreSQL, Redis, APIs, and Web.",
    description: "Setup complex microservices in a single command. Includes Docker Compose scripts for NextJS, Django, NodeJS, PostgreSQL, Redis, Nginx configurations, and automated SSL cert renewal setups.",
    category: "scripts",
    subcategory: "devops-cicd-pipelines",
    tags: "docker,devops,compose,postgres,redis",
    thumbnail: "https://images.unsplash.com/photo-1597852074816-d933c4d2b988?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/docker/awesome-compose/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 4. Design Assets (design-assets)
  {
    id: "free-flowbite",
    title: "Flowbite CSS Component Kit - Premium Responsive Tailwind CSS UI Library",
    slug: "flowbite-tailwind-components-library",
    shortDescription: "A premium package of over 400+ interactive Tailwind CSS components, utility classes, and layouts.",
    description: "Copy-paste production UI components in seconds. Flowbite compiles modals, navbar layouts, form inputs, analytics tables, buttons, accordion elements, and sidebar menus styled perfectly with Tailwind CSS.",
    category: "design-assets",
    subcategory: "tailwind-css-component-kits",
    tags: "tailwind,ui,components,figma,css",
    thumbnail: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/themesberg/flowbite/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-merakiui",
    title: "Meraki UI Tailwind CSS Components - High-Conversion Marketing Layout Kits",
    slug: "merakiui-tailwind-conversion-layouts",
    shortDescription: "Visual components collection built with Tailwind CSS supporting responsive RTL and dark modes.",
    description: "Beautifully styled CTA cards, testimonials sections, hero banners, grids, pricing cards, and footer layouts. Designed to improve marketing website conversions and copy-paste directly into React templates.",
    category: "design-assets",
    subcategory: "tailwind-css-component-kits",
    tags: "tailwind,ui-kit,marketing,html,rtl",
    thumbnail: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/merakiui/merakiui/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-lucide",
    title: "Lucide Vector SVG Custom Icon Library - High-Performance Developer Asset Pack",
    slug: "lucide-svg-custom-icon-library",
    shortDescription: "Beautifully designed, pixel-perfect line icons package in SVG format for websites and apps.",
    description: "Lucide is an open-source SVG line icon set. Contains 1000+ custom vector icons built for speed and consistent alignment. Optimized for imports to keep your Next.js application bundles minimal.",
    category: "design-assets",
    subcategory: "custom-svg-icon-libraries",
    tags: "icons,svg,design,developer,react",
    thumbnail: "https://images.unsplash.com/photo-1550439062-609e1531270e?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/lucide-icons/lucide/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 5. AI Prompts (ai-prompts)
  {
    id: "free-chatgpt-prompts",
    title: "Awesome ChatGPT Prompt Engineering System Pack - Advanced Developer Templates",
    slug: "awesome-chatgpt-prompt-engineering",
    shortDescription: "A massive list of ChatGPT prompt templates designed to optimize developer LLM contexts.",
    description: "Get precise coding outputs from ChatGPT and Claude. This guide includes system prompt formulas to configure LLMs as SQL schema optimizers, unit-test generators, bug finders, and tech copywriters.",
    category: "ai-prompts",
    subcategory: "developer-prompt-engineering",
    tags: "gpt,prompts,ai,chatgpt,engineering",
    thumbnail: "https://images.unsplash.com/photo-1675271591211-126ad94c495d?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/f/awesome-chatgpt-prompts/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-fabric-ai",
    title: "Fabric Custom AI System Prompts & Orchestrations - LLM Context Amplifiers",
    slug: "fabric-custom-ai-system-prompts",
    shortDescription: "Structured prompts templates designed to summarize files, write guides, and analyze code bases.",
    description: "Fabric is an orchestration platform designed to help humans amplify their cognitive flow using AI. Includes detailed, markdown prompt recipes built for writing essays, code auditing, and text summaries.",
    category: "ai-prompts",
    subcategory: "developer-prompt-engineering",
    tags: "ai,prompts,fabric,llm,command-line",
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/danielmiessler/fabric/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-llamaindex-prompts",
    title: "LlamaIndex Structured LLM Prompts & RAG Recipes - Custom Context Templates",
    slug: "llamaindex-structured-llm-prompts",
    shortDescription: "Context prompts templates and recipes optimized for Retrieval-Augmented Generation (RAG).",
    description: "Learn how to format instructions to extract structured data from PDF manuals, query database documents, and write copy utilizing LlamaIndex search patterns.",
    category: "ai-prompts",
    subcategory: "marketing-copywriter-prompts",
    tags: "rag,prompts,ai,llamaindex,python",
    thumbnail: "https://images.unsplash.com/photo-1673187115862-3ba5995f915c?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/run-llama/llama_index/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 6. Ebooks & Playbooks (ebooks)
  {
    id: "free-indie-hackers",
    title: "Indie Hackers Checklist & Launch Playbook Ebook - Actionable Solo Startup Guide",
    slug: "indie-hackers-checklist-launch-playbook-ebook",
    shortDescription: "Monetize code efficiently. Actionable startup guide checklist detailing product validation.",
    description: "Learn how to validate ideas, write marketing copy, configure auto-checkout solutions, find target developer audiences, and construct viral loops using this comprehensive solo entrepreneur manual.",
    category: "ebooks",
    subcategory: "launch-marketing-playbooks",
    tags: "ebook,startup,guide,monetization,indie",
    thumbnail: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/vincanger/indie-hackers-checklist/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-frontend-checklist",
    title: "Front-End Developer SEO Checklist & Playbook - Complete Search Engine Optimization Guide",
    slug: "frontend-developer-seo-checklist-playbook",
    shortDescription: "Optimizations checklist handbook for front-end sites covering meta tags, SEO, and speeds.",
    description: "The classic front-end checklist handbook. Optimize SEO metadata, title tags, responsiveness parameters, accessibility protocols, performance metrics, and caching setups to rank on Google search pages.",
    category: "ebooks",
    subcategory: "seo-checklists",
    tags: "seo,frontend,checklist,handbook,speed",
    thumbnail: "https://images.unsplash.com/photo-1522252234503-e356532cafd5?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/thedaviddias/Front-End-Checklist/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-system-design",
    title: "System Design Primer & Coding Handbook - Advanced Architecture & Scalability Playbook",
    slug: "system-design-primer-coding-handbook",
    shortDescription: "A comprehensive guide on learning how to design large-scale web systems and scale APIs.",
    description: "Learn scalability concepts from the ground up. This primer handbook explains load balancing architectures, database replication, CDN edge routing, microservice designs, API security, and server-side caching setups.",
    category: "ebooks",
    subcategory: "coding-handbooks",
    tags: "architecture,scaling,handbook,guide,system-design",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc51?q=80&w=600&auto=format&fit=crop",
    fileUrl: "https://github.com/donnemartin/system-design-primer/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
];

async function seed() {
  console.log("Cleaning old free products first...");
  await db.delete(products).where(like(products.id, "free-%"));
  
  console.log("Starting to seed verified free open-source projects into DB...");
  let count = 0;

  for (const proj of FREE_PROJECTS) {
    try {
      console.log(`Inserting free product: "${proj.title}"...`);
      await db.insert(products).values({
        ...proj,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      count++;
    } catch (err) {
      console.error(`Error processing project "${proj.title}":`, err);
    }
  }

  console.log(`Successfully seeded ${count} free products into Neon DB!`);
}

seed().catch(console.error);
