import { db } from "../db";
import { products } from "../db/schema";
import { eq } from "drizzle-orm";

const FREE_PROJECTS = [
  // 1. SaaS Templates (saas-templates)
  {
    id: "free-shadcn-taxonomy",
    title: "Taxonomy Next.js SaaS Boilerplate - Premium Ready-To-Deploy Template",
    slug: "taxonomy-nextjs-saas-boilerplate",
    shortDescription: "An open-source application built using Next.js 13/14 App Router, Prisma ORM, NextAuth, and Stripe subscriptions.",
    description: "Taxonomy is a complete, production-ready Next.js SaaS template demonstrating standard web application architecture. Features user authentication with NextAuth, database migrations with Prisma, transactional email flows, and a clean Stripe subscription check out flow. Written with state-of-the-art Tailwind CSS UI layouts.",
    category: "saas-templates",
    subcategory: "nextjs-react-boilerplates",
    tags: "nextjs,saas,boilerplate,stripe,prisma",
    thumbnail: "https://opengraph.githubassets.com/1/shadcn-ui/taxonomy",
    fileUrl: "https://github.com/shadcn-ui/taxonomy/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-vercel-payments",
    title: "Next.js Subscription Payments Boilerplate - Stripe & Supabase SaaS Starter Kit",
    slug: "nextjs-subscription-payments-boilerplate",
    shortDescription: "All-in-one subscription billing starter kit featuring Stripe Checkout, Customer Portal, and Supabase integration.",
    description: "The official Next.js template by Vercel for high-performance subscription billing. Get instant access to integrated Stripe Checkout setups, automated webhook listeners, user profile settings, Stripe Customer Portal redirects, and secure Supabase database bindings.",
    category: "saas-templates",
    subcategory: "nextjs-react-boilerplates",
    tags: "nextjs,stripe,supabase,auth,billing",
    thumbnail: "https://opengraph.githubassets.com/1/vercel/nextjs-subscription-payments",
    fileUrl: "https://github.com/vercel/nextjs-subscription-payments/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-fastapi-template",
    title: "FastAPI Production Backend Boilerplate - Advanced High-Performance Python API Framework",
    slug: "fastapi-production-backend-boilerplate",
    shortDescription: "A fully configurable, production-ready FastAPI project template with SQLAlchemy, Postgres, Redis, and Docker.",
    description: "An advanced Python backend starter kit powered by FastAPI. Includes pre-configured templates for SQLAlchemy 2.0 ORM, Redis API caching, Alembic database migrations, Pytest coverage testing, Docker Compose configurations, and automated swagger documentation.",
    category: "saas-templates",
    subcategory: "python-backends",
    tags: "fastapi,python,redis,docker,api",
    thumbnail: "https://opengraph.githubassets.com/1/artemonim/fastapi_template",
    fileUrl: "https://github.com/artemonim/fastapi_template/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-nestjs-boilerplate",
    title: "NestJS Enterprise REST API Boilerplate - Clean Architecture & Postgres Starter",
    slug: "nestjs-enterprise-rest-api-boilerplate",
    shortDescription: "Enterprise-grade NestJS boilerplate featuring Postgres, TypeORM, JWT auth, mailing, and Docker setup.",
    description: "A professional starter kit for building highly scalable enterprise backends with NestJS. Fully equipped with TypeORM, Postgres, JWT authentication guards, third-party logins (Facebook, Google), password resets, email verification services, and ready Docker configurations.",
    category: "saas-templates",
    subcategory: "rest-apis-microservices",
    tags: "nestjs,typescript,postgres,typeorm,docker",
    thumbnail: "https://opengraph.githubassets.com/1/brocoders/nestjs-boilerplate",
    fileUrl: "https://github.com/brocoders/nestjs-boilerplate/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-scaffold-eth",
    title: "Scaffold-ETH 2 - Decentralized Application (dApp) Starter Kit & Hardhat Boilerplate",
    slug: "scaffold-eth-2-dapp-starter-kit",
    shortDescription: "A modern, clean tool for prototyping Ethereum dApps with Hardhat/Foundry, Wagmi, and RainbowKit.",
    description: "The ultimate developer setup to write, test, and deploy Ethereum smart contracts. Scaffold-ETH 2 links smart contracts (Hardhat or Foundry) with a clean React web frontend. Pre-configured with Wagmi Hooks, Viem, and RainbowKit wallet connectors.",
    category: "saas-templates",
    subcategory: "web3-crypto-templates",
    tags: "solidity,ethereum,hardhat,react,wagmi",
    thumbnail: "https://opengraph.githubassets.com/1/scaffold-eth/scaffold-eth-2",
    fileUrl: "https://github.com/scaffold-eth/scaffold-eth-2/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 2. Landing Pages (landing-pages)
  {
    id: "free-threejs-portfolio",
    title: "Three.js React Three Fiber GSAP Portfolio - High-Fidelity 3D Developer Website Template",
    slug: "threejs-react-three-fiber-gsap-portfolio",
    shortDescription: "A visually rich 3D personal portfolio template utilizing React Three Fiber, GSAP, and Tailwind CSS.",
    description: "Stand out from the crowd with an interactive 3D landing page portfolio. Includes pre-configured React Three Fiber grids, OrbitControls for perspective viewing, smooth GSAP animations, custom shaders, and fully responsive CSS layouts.",
    category: "landing-pages",
    subcategory: "gsap-3d-animated-pages",
    tags: "threejs,react,gsap,3d,portfolio",
    thumbnail: "https://opengraph.githubassets.com/1/designcode-io/threejs-portfolio",
    fileUrl: "https://github.com/designcode-io/threejs-portfolio/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-precedent",
    title: "Precedent Next.js Marketing Template - High-Converting Waitlist & Launch Page",
    slug: "precedent-nextjs-marketing-template",
    shortDescription: "An opinionated, beautifully designed Next.js launch landing page template optimized for performance.",
    description: "Precedent is a clean product launch landing page built with Next.js App Router, Framer Motion transitions, Lucide React icons, Radix UI primitives, Tailwind CSS styles, and a pre-configured waitlist collection field.",
    category: "landing-pages",
    subcategory: "waitlist-newsletter-pages",
    tags: "nextjs,tailwind,framer-motion,landing",
    thumbnail: "https://opengraph.githubassets.com/1/steven-tey/precedent",
    fileUrl: "https://github.com/steven-tey/precedent/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-stripe-pricing-table",
    title: "Stripe Conversional SaaS Pricing Component - Premium Checkout Funnel Templates",
    slug: "stripe-conversional-saas-pricing-component",
    shortDescription: "Pricing component layouts built to maximize checkout flow conversions and integrate Stripe billing.",
    description: "A clean pricing card layout optimized for SaaS conversion rates. Includes responsive comparison tables, checkmark features, billing interval toggle switches (annual/monthly), and easy linking structures to Stripe Customer checkout.",
    category: "landing-pages",
    subcategory: "saas-pricing-checkout",
    tags: "stripe,pricing,components,checkout",
    thumbnail: "https://opengraph.githubassets.com/1/stripe-samples/stripe-pricing-table",
    fileUrl: "https://github.com/stripe-samples/stripe-pricing-table/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-gatsby-portfolio",
    title: "Gatsby Simple Modern Portfolio - Premium Creative Developer Showcase Layout",
    slug: "gatsby-simple-modern-developer-portfolio",
    shortDescription: "A simple and clean developer portfolio template built with Gatsby.js, React, and Bootstrap.",
    description: "A highly customizable and responsive portfolio theme for web developers. Built on Gatsby for lightning-fast speeds, featuring smooth scrolling animations, modern sections, contact forms, and automated build scripts.",
    category: "landing-pages",
    subcategory: "agency-portfolio-pages",
    tags: "gatsby,react,portfolio,landing,theme",
    thumbnail: "https://opengraph.githubassets.com/1/cobidev/gatsby-simpleportfolio",
    fileUrl: "https://github.com/cobidev/gatsby-simpleportfolio/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-astrowind",
    title: "AstroWind Premium Landing Page Template - Modern High-Performance Astro Theme",
    slug: "astrowind-premium-landing-page-template",
    shortDescription: "A modern, SEO-friendly landing page template designed with Astro 4.0 and Tailwind CSS.",
    description: "AstroWind is a highly customizable, responsive starter template designed with Astro and Tailwind CSS. Highly optimized for page speed performance, featuring SEO tags setup, blog module, and 100/100 Lighthouse metrics.",
    category: "landing-pages",
    subcategory: "no-code-themes",
    tags: "astro,tailwind,landing,seo,speed",
    thumbnail: "https://opengraph.githubassets.com/1/onwidget/astrowind",
    fileUrl: "https://github.com/onwidget/astrowind/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 3. Scripts & Automations (scripts)
  {
    id: "free-crawlee",
    title: "Crawlee Node.js Resilient Web Scraper & Crawler - Puppeteer, Playwright & Cheerio Automation",
    slug: "crawlee-nodejs-resilient-web-scraper",
    shortDescription: "A web scraping and browser automation library for Node.js to scrape links and extract structured data.",
    description: "Crawlee helps you build resilient web scrapers that bypass anti-scraping blocks automatically. Handles proxy rotation, request queues, request retries, automated link discovery, and structured data storage (JSON/CSV) effortlessly.",
    category: "scripts",
    subcategory: "web-scrapers-crawlers",
    tags: "scraping,crawler,puppeteer,playwright,nodejs",
    thumbnail: "https://opengraph.githubassets.com/1/apify/crawlee",
    fileUrl: "https://github.com/apify/crawlee/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-chrome-boilerplate",
    title: "Chrome Extension React Manifest V3 Boilerplate - Webpack & hot reloading starter",
    slug: "chrome-extension-react-mv3-boilerplate",
    shortDescription: "A premium Manifest V3 extension developer boilerplate with React, Webpack, and hot reloading.",
    description: "Build browser extensions instantly. This starter kit complies with Chrome Manifest V3 regulations and is pre-configured with React, TypeScript, Webpack compilation pipelines, background script setups, and extension popup windows.",
    category: "scripts",
    subcategory: "browser-extensions",
    tags: "chrome,extension,manifest-v3,react,webpack",
    thumbnail: "https://opengraph.githubassets.com/1/lxieyang/chrome-extension-boilerplate-react",
    fileUrl: "https://github.com/lxieyang/chrome-extension-boilerplate-react/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-twitter-bot",
    title: "Spry Social Media Automation Script - Twitter Agent Scheduler & Analytics Bot",
    slug: "spry-social-media-automation-script",
    shortDescription: "Social media automation helper script to queue posts, schedule tweets, and sync analytical data.",
    description: "An automated helper script to maintain developer profile content. Allows scheduling tweets, setting content queues, running automated keyword listening scripts, and dispatching analytics summaries directly to discord webhooks.",
    category: "scripts",
    subcategory: "social-media-bots",
    tags: "bot,twitter,automation,script,marketing",
    thumbnail: "https://opengraph.githubassets.com/1/PLhery/spry",
    fileUrl: "https://github.com/PLhery/spry/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-docker-compose",
    title: "Docker Awesome Compose Boilerplates - One-Click Production Environment Configurations",
    slug: "docker-awesome-compose-boilerplates",
    shortDescription: "A collection of production-ready Docker Compose environment scripts for PostgreSQL, Redis, APIs, and Web.",
    description: "Setup complex microservices in a single command. Includes Docker Compose scripts for NextJS, Django, NodeJS, PostgreSQL, Redis, Nginx configurations, and automated SSL cert renewal setups.",
    category: "scripts",
    subcategory: "devops-cicd-pipelines",
    tags: "docker,devops,compose,postgres,redis",
    thumbnail: "https://opengraph.githubassets.com/1/awesome-compose/awesome-compose",
    fileUrl: "https://github.com/awesome-compose/awesome-compose/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-autogpt",
    title: "AutoGPT Workflows Automation Command Script - Autonomous LLM Agent Loop",
    slug: "autogpt-workflows-automation-script",
    shortDescription: "Experimental terminal automation tool that orchestrates LLMs in a loop to write code and search web.",
    description: "An autonomous agent system linking LLMs together to perform goals. Set instructions via terminal prompts, allowing the agent to write custom scripts, compile research briefs, debug code blocks, and output local files autonomously.",
    category: "scripts",
    subcategory: "script-automation-macros",
    tags: "ai,agent,python,gpt,automation",
    thumbnail: "https://opengraph.githubassets.com/1/Significant-Gravitas/AutoGPT",
    fileUrl: "https://github.com/Significant-Gravitas/AutoGPT/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 4. Design Assets (design-assets)
  {
    id: "free-flowbite",
    title: "Flowbite CSS Component Kit - Premium Responsive Tailwind CSS UI Library",
    slug: "flowbite-tailwind-components-library",
    shortDescription: "A premium package of over 400+ interactive Tailwind CSS components, utility classes, and layouts.",
    description: "Copy-paste production UI components in seconds. Flowbite compiles modals, navbar layouts, form inputs, analytics tables, buttons, accordion elements, and sidebar menus styled perfectly with Tailwind CSS.",
    category: "design-assets",
    subcategory: "tailwind-css-component-kits",
    tags: "tailwind,ui,components,figma,css",
    thumbnail: "https://opengraph.githubassets.com/1/themesberg/flowbite",
    fileUrl: "https://github.com/themesberg/flowbite/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-merakiui",
    title: "Meraki UI Tailwind CSS Components - High-Conversion Marketing Layout Kits",
    slug: "merakiui-tailwind-conversion-layouts",
    shortDescription: "Visual components collection built with Tailwind CSS supporting responsive RTL and dark modes.",
    description: "Beautifully styled CTA cards, testimonials sections, hero banners, grids, pricing cards, and footer layouts. Designed to improve marketing website conversions and copy-paste directly into React templates.",
    category: "design-assets",
    subcategory: "tailwind-css-component-kits",
    tags: "tailwind,ui-kit,marketing,html,rtl",
    thumbnail: "https://opengraph.githubassets.com/1/merakiui/merakiui",
    fileUrl: "https://github.com/merakiui/merakiui/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-figma-fb",
    title: "Facebook Design System Figma Component Files - Premium UI Toolkit Asset Pack",
    slug: "facebook-design-system-figma-kit",
    shortDescription: "Official Figma files containing layouts, icons, buttons, and design system variables for designers.",
    description: "Upgrade your design systems with official Figma layout files. Mapped cleanly with auto-layout variables, dark/light theme options, responsive margins, typography sheets, and custom UI components.",
    category: "design-assets",
    subcategory: "figma-ui-kits-design-systems",
    tags: "figma,design,ui,ux,templates",
    thumbnail: "https://opengraph.githubassets.com/1/facebook/design",
    fileUrl: "https://github.com/facebook/design/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-lucide",
    title: "Lucide Vector SVG Custom Icon Library - High-Performance Developer Asset Pack",
    slug: "lucide-svg-custom-icon-library",
    shortDescription: "Beautifully designed, pixel-perfect line icons package in SVG format for websites and apps.",
    description: "Lucide is an open-source SVG line icon set. Contains 1000+ custom vector icons built for speed and consistent alignment. Optimized for imports to keep your Next.js application bundles minimal.",
    category: "design-assets",
    subcategory: "custom-svg-icon-libraries",
    tags: "icons,svg,design,developer,react",
    thumbnail: "https://opengraph.githubassets.com/1/lucide-icons/lucide",
    fileUrl: "https://github.com/lucide-icons/lucide/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-humaans",
    title: "Humaans Custom SVG Illustration Pack - Premium Landing Page Graphic Elements",
    slug: "humaans-custom-svg-illustration-pack",
    shortDescription: "Mix-and-match custom SVG illustration elements designed to build premium landing page scenes.",
    description: "Designed by Pablo Stanley, Humaans is a beautiful vector illustration template to add high-fidelity graphics to landing pages. Swap hairs, clothes, positions, and backgrounds to construct engaging marketing scenes.",
    category: "design-assets",
    subcategory: "3d-models-illustrations",
    tags: "svg,graphics,illustration,design,vector",
    thumbnail: "https://opengraph.githubassets.com/1/pablostanley/humaans",
    fileUrl: "https://github.com/pablostanley/humaans/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 5. AI Prompts (ai-prompts)
  {
    id: "free-chatgpt-prompts",
    title: "Awesome ChatGPT Prompt Engineering System Pack - Advanced Developer Templates",
    slug: "awesome-chatgpt-prompt-engineering",
    shortDescription: "A massive list of ChatGPT prompt templates designed to optimize developer LLM contexts.",
    description: "Get precise coding outputs from ChatGPT and Claude. This guide includes system prompt formulas to configure LLMs as SQL schema optimizers, unit-test generators, bug finders, and tech copywriters.",
    category: "ai-prompts",
    subcategory: "developer-prompt-engineering",
    tags: "gpt,prompts,ai,chatgpt,engineering",
    thumbnail: "https://opengraph.githubassets.com/1/f/awesome-chatgpt-prompts",
    fileUrl: "https://github.com/f/awesome-chatgpt-prompts/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-fabric-ai",
    title: "Fabric Custom AI System Prompts & Orchestrations - LLM Context Amplifiers",
    slug: "fabric-custom-ai-system-prompts",
    shortDescription: "Structured prompts templates designed to summarize files, write guides, and analyze code bases.",
    description: "Fabric is an orchestration platform designed to help humans amplify their cognitive flow using AI. Includes detailed, markdown prompt recipes built for writing essays, code auditing, and text summaries.",
    category: "ai-prompts",
    subcategory: "developer-prompt-engineering",
    tags: "ai,prompts,fabric,llm,command-line",
    thumbnail: "https://opengraph.githubassets.com/1/danielmiessler/fabric",
    fileUrl: "https://github.com/danielmiessler/fabric/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-llamaindex-prompts",
    title: "LlamaIndex Structured LLM Prompts & RAG Recipes - Custom Context Templates",
    slug: "llamaindex-structured-llm-prompts",
    shortDescription: "Context prompts templates and recipes optimized for Retrieval-Augmented Generation (RAG).",
    description: "Learn how to format instructions to extract structured data from PDF manuals, query database documents, and write copy utilizing LlamaIndex search patterns.",
    category: "ai-prompts",
    subcategory: "marketing-copywriter-prompts",
    tags: "rag,prompts,ai,llamaindex,python",
    thumbnail: "https://opengraph.githubassets.com/1/run-llama/llama_index",
    fileUrl: "https://github.com/run-llama/llama_index/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-midjourney-style",
    title: "Midjourney Photorealistic Prompts & Style Guide Recipe - Premium Visual Presets",
    slug: "midjourney-photorealistic-prompts-guide",
    shortDescription: "Prompt formulas and style guide to generate beautiful photorealistic illustrations and mockups.",
    description: "Generate gorgeous visuals for landing pages. Includes Midjourney syntax guides, camera specifications (aperture, focal lengths), color palettes recipes, and lighting keywords to build stunning marketing assets.",
    category: "ai-prompts",
    subcategory: "creative-ai-recipes",
    tags: "midjourney,art,prompts,graphics,ai",
    thumbnail: "https://opengraph.githubassets.com/1/willwulfken/Midjourney-Guide",
    fileUrl: "https://github.com/willwulfken/Midjourney-Guide/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-babyagi-agent",
    title: "BabyAGI Autonomous AI Task Agent Core Profile - System Execution Templates",
    slug: "babyagi-autonomous-task-agent",
    shortDescription: "A Python script orchestrating autonomous OpenAI task prioritization loops in a workflow.",
    description: "Analyze autonomous agent loops. This template outlines BabyAGI settings to execute objectives, generate new tasks dynamically based on results, and prioritize actions within vector databases.",
    category: "ai-prompts",
    subcategory: "autonomous-ai-agents",
    tags: "agi,agent,openai,python,tasks",
    thumbnail: "https://opengraph.githubassets.com/1/yoheinakajima/babyagi",
    fileUrl: "https://github.com/yoheinakajima/babyagi/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },

  // 6. Ebooks & Playbooks (ebooks)
  {
    id: "free-product-hunt",
    title: "Product Hunt Viral Launch Marketing Playbook - Comprehensive Creator Marketing Guide",
    slug: "product-hunt-viral-launch-marketing-playbook",
    shortDescription: "Actionable checklist handbook outlining step-by-step strategies to launch digital products.",
    description: "The ultimate marketing handbook for launching digital assets on Product Hunt. Covers pre-launch list building, visual copy formulas, comment frameworks, badges integration, and tracking lists.",
    category: "ebooks",
    subcategory: "launch-marketing-playbooks",
    tags: "marketing,playbook,launch,product-hunt,growth",
    thumbnail: "https://opengraph.githubassets.com/1/gokulkrishh/awesome-product-hunt",
    fileUrl: "https://github.com/gokulkrishh/awesome-product-hunt/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-indie-hackers",
    title: "Indie Hackers Checklist & Launch Playbook Ebook - Actionable Solo Startup Guide",
    slug: "indie-hackers-checklist-launch-playbook-ebook",
    shortDescription: "Monetize code efficiently. Actionable startup guide checklist detailing product validation.",
    description: "Learn how to validate ideas, write marketing copy, configure auto-checkout solutions, find target developer audiences, and construct viral loops using this comprehensive solo entrepreneur manual.",
    category: "ebooks",
    subcategory: "launch-marketing-playbooks",
    tags: "ebook,startup,guide,monetization,indie",
    thumbnail: "https://opengraph.githubassets.com/1/vincanger/indie-hackers-checklist",
    fileUrl: "https://github.com/vincanger/indie-hackers-checklist/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-frontend-checklist",
    title: "Front-End Developer SEO Checklist & Playbook - Complete Search Engine Optimization Guide",
    slug: "frontend-developer-seo-checklist-playbook",
    shortDescription: "Optimizations checklist handbook for front-end sites covering meta tags, SEO, and speeds.",
    description: "The classic front-end checklist handbook. Optimize SEO metadata, title tags, responsiveness parameters, accessibility protocols, performance metrics, and caching setups to rank on Google search pages.",
    category: "ebooks",
    subcategory: "seo-checklists",
    tags: "seo,frontend,checklist,handbook,speed",
    thumbnail: "https://opengraph.githubassets.com/1/thedaviddias/Front-End-Checklist",
    fileUrl: "https://github.com/thedaviddias/Front-End-Checklist/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-system-design",
    title: "System Design Primer & Coding Handbook - Advanced Architecture & Scalability Playbook",
    slug: "system-design-primer-coding-handbook",
    shortDescription: "A comprehensive guide on learning how to design large-scale web systems and scale APIs.",
    description: "Learn scalability concepts from the ground up. This primer handbook explains load balancing architectures, database replication, CDN edge routing, microservice designs, API security, and server-side caching setups.",
    category: "ebooks",
    subcategory: "coding-handbooks",
    tags: "architecture,scaling,handbook,guide,system-design",
    thumbnail: "https://opengraph.githubassets.com/1/donnemartin/system-design-primer",
    fileUrl: "https://github.com/donnemartin/system-design-primer/archive/refs/heads/master.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
  {
    id: "free-side-project-guide",
    title: "Developer Side-Project Creator Business Guide - Monetization & Coding Playbook",
    slug: "developer-side-project-business-guide",
    shortDescription: "Build, launch, and monetize. Actionable handbook outlining strategies to sell scripts online.",
    description: "Learn how to turn code lines into dollar earnings. Covers project selection, developer branding guide, monetization mechanics, and organic marketing loops to acquire customers.",
    category: "ebooks",
    subcategory: "creator-business-guides",
    tags: "side-project,monetize,playbook,creator,marketing",
    thumbnail: "https://opengraph.githubassets.com/1/KalleHallden/Side-Project-Guide",
    fileUrl: "https://github.com/KalleHallden/Side-Project-Guide/archive/refs/heads/main.zip",
    price: 0,
    isFree: true,
    version: "1.0.0",
    featured: false,
    published: true,
    status: "approved",
  },
];

async function seed() {
  console.log("Starting to seed free open-source projects into DB...");
  let count = 0;

  for (const proj of FREE_PROJECTS) {
    try {
      // Check if product already exists
      const existing = await db.query.products.findFirst({
        where: eq(products.id, proj.id),
      });

      if (existing) {
        console.log(`Product "${proj.title}" already exists. Updating details...`);
        await db
          .update(products)
          .set({
            title: proj.title,
            slug: proj.slug,
            shortDescription: proj.shortDescription,
            description: proj.description,
            category: proj.category,
            subcategory: proj.subcategory,
            tags: proj.tags,
            thumbnail: proj.thumbnail,
            fileUrl: proj.fileUrl,
            price: proj.price,
            isFree: proj.isFree,
            version: proj.version,
            featured: proj.featured,
            published: proj.published,
            status: proj.status,
            updatedAt: new Date(),
          })
          .where(eq(products.id, proj.id));
      } else {
        console.log(`Inserting new free product: "${proj.title}"...`);
        await db.insert(products).values({
          ...proj,
          createdAt: new Date(),
          updatedAt: new Date(),
        });
      }
      count++;
    } catch (err) {
      console.error(`Error processing project "${proj.title}":`, err);
    }
  }

  console.log(`Successfully seeded ${count} free products into Neon DB!`);
}

seed().catch(console.error);
